default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: 172.18.0.1  # Aqui você coloca o IP da sua máquina
  port: 5432

development:
  <<: *default
  database: gestpat

